"""Add PredictionLog model

Revision ID: bc5d658f6120
Revises: 20260325_0003
Create Date: 2026-03-26 15:30:59.743693+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5d658f6120'
down_revision: Union[str, None] = '20260325_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('per_key_metrics', schema=None) as batch_op:
        batch_op.alter_column('accuracy',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index('ix_per_key_metrics_updated_at')
        batch_op.create_index(batch_op.f('ix_per_key_metrics_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('prediction_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_logs_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_logs_version_id'), ['version_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_logs_version_id'))
        batch_op.drop_index(batch_op.f('ix_prediction_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_prediction_logs_key'))
        batch_op.drop_index(batch_op.f('ix_prediction_logs_id'))

    with op.batch_alter_table('per_key_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_per_key_metrics_timestamp'))
        batch_op.create_index('ix_per_key_metrics_updated_at', ['updated_at'], unique=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('accuracy',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
