global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
        labels:
          stack: pskc
          service: prometheus

  - job_name: pskc-api
    metrics_path: /metrics/prometheus
    static_configs:
      - targets:
          - api:8000
        labels:
          stack: pskc
          service: api
